### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by orangy** [stufreen/web-drum-sequencer#14]
Thanks for this awesome project! I enjoy it very much :) However…

With `npm install` it shows warnings for vulnerabilities: 
> found 1181 vulnerabilities (64 low, 3 moderate, 1113 high, 1 critical)

`npm audit fix` reported:
> fixed 1124 of 1181 vulnerabilities in 33174 scanned packages
>  1 vulnerability required manual review and could not be updated
>  2 package updates for 56 vulnerabilities involved breaking changes

What is left:
> found 57 vulnerabilities (55 low, 2 high)

Not even sure it will run after all these changes…

**Comment by stufreen** [comment]
Thanks @orangy! Should be fixed by https://github.com/stufreen/web-drum-sequencer/pull/16
